#!/bin/bash

if [ $# == 0 ]; then
  echo "Missing argument" 1>&2
  echo "Usage: '$0 [aws|azure|gcp]'" 1>&2
  exit 1
fi

set -exu

if [ "${@}" == "aws" ]; then
  pushd terraform/aws
    go-bindata -pkg aws -mode 0740 -o templates.go templates
  popd
fi

if [ "${@}" == "azure" ]; then
  pushd terraform/azure
    go-bindata -pkg azure -mode 0740 -o templates.go templates
  popd
fi

if [ "${@}" == "gcp" ]; then
  pushd terraform/gcp
    go-bindata -pkg gcp -mode 0740 -o templates.go templates
  popd
fi
